### ISSUE TITLE
Cannot `go install github.com/air-verse/air@latest`

### ISSUE THREAD

**Issue by nevinsm** [air-verse/air#605] opened 2024-06-03 23:32 UTC
It looks like a new tag hasn't been added yet so when go grabs latest it is the old version and it errors out.

Error message:
```
go: downloading github.com/air-verse/air v1.52.1
go: github.com/air-verse/air@latest: version constraints conflict:
        github.com/air-verse/air@v1.52.1: parsing go.mod:
        module declares its path as: github.com/cosmtrek/air
                but was required as: github.com/air-verse/air
```

**Comment by xiantang** [comment] 2024-06-04 01:14
still have issue , so i revert the PR

**Comment by raymondjacobson** [comment] 2024-06-04 02:16
+1 seeing this as well

**Comment by xiantang** [comment] 2024-06-04 02:17
> +1 seeing this as well

I just revert the PR, still have issue?

**Comment by fadiinho** [comment] 2024-06-04 02:20
> > +1 seeing this as well
> 
> I just revert the PR, still have issue?

Yep, I'm still having the same error

**Comment by xiantang** [comment] 2024-06-04 02:25
just use the document one.

**Comment by kz23szk** [comment] 2024-06-04 02:30
Currently, I can't install `github.com/cosmtrek/air`、 but will the module name be `github.com/air-verse/air` in the end?
I want to know which one it will be.

**Comment by xiantang** [comment] 2024-06-04 02:45
will be github.com/air-verse/air in the end.

**Comment by xiantang** [comment] 2024-06-04 02:55
![image](https://github.com/air-verse/air/assets/34479567/b8906749-89ff-446e-a68b-8ded6de4edfb)
should be fixed. I've tested in docker container.

**Comment by franckffv** [comment] 2024-06-04 07:27
For me, I had to replace `github.com/cosmtrek/air@latest` with `github.com/air-verse/air@latest` in my Docker Compose, as the URL `github.com/cosmtrek/air` redirects to `github.com/air-verse/air`

**Comment by silverwind** [comment] 2024-06-04 10:20
This change broke all past versions of air as it's no longer possible to install anything but the latest version. Go module system is broken by design 😆.

**Comment by nevinsm** [comment] 2024-06-04 16:37
A proper fix for this will require some git history rewriting. The go module system is designed to be stable so changing the name like this will cause these expected integrity issues. You will need to rewrite references in all the commits so that all tags have the new `github.com/air-verse/air` instead of `github.com/cosmtrek/air` for module references. The same with the runner references and any other submodules.

e.g.
v1.49.0 https://github.com/air-verse/air/blob/v1.49.0/go.mod#L1

should look like v1.52.2 https://github.com/air-verse/air/blob/v1.52.2/go.mod

Should be doable with `git filter-repo --replace-text <(echo 'github.com/cosmtrek/air==>github.com/air-verse/air')`. Be aware that rewriting git history can have seriously bad side effects.

It might be better to leave v1 up at github.com/cosmtrek/air and make air-verse/air the v2 release with the original repo archived instead of redirecting.

**Comment by nevinsm** [comment] 2024-06-04 16:49
FWIW My personal preference for how to handle this would be to archive and leave up the original repository with a note that it is deprecated and moved here. Start this one fresh with a commit that changes the names and then tag it as v2.0.0 to reflect the breaking change. You lose the old git history, but then the bifurcation is clean at least.

**Comment by jarielbalberona** [comment] 2024-07-26 01:55
I got this error. Any update?

**Closed** 2024-09-21 15:01 UTC

**Comment by gnpaone** [comment] 2024-10-24 04:38
![image](https://github.com/user-attachments/assets/37a519dc-f196-468a-80da-b2af2a794ad0)

Same error again

**Comment by linhdtk-0323** [comment] 2025-05-13 10:11
Now im having the same error although i changed into "air-verse/air@latest"

<img width="1065" alt="Image" src="https://github.com/user-attachments/assets/0f7aa9d4-11a1-4ac1-9419-f9b9b591a176" />
