### ISSUE TITLE
Segfault When `air` Command Ran

### ISSUE THREAD

**Issue by temidaradev** [air-verse/air#668] opened 2024-10-19 20:37 UTC
I got a segfault when I try to run the command `air` but when I reset my PC and run `air` again it refreshes my page but I instantly get segfault
```
watching public
!exclude tmp
watching views
watching views/auth
watching views/components
watching views/css
watching views/home
watching views/layouts
building...
running...
building static files for development
2024/10/19 23:20:29 INFO HTTPS Server Started listenAddr=:3000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x5ec12a0]

goroutine 40 [running]:
regexp.(*Regexp).doExecute(0xc0000b2780?, {0x0?, 0x0?}, {0xc00024a120?, 0x5d?, 0x60?}, {0x0?, 0x0?}, 0x0?, 0x0, ...)
        /usr/local/go/src/regexp/exec.go:527 +0x80
regexp.(*Regexp).doMatch(...)
        /usr/local/go/src/regexp/exec.go:514
regexp.(*Regexp).Match(...)
        /usr/local/go/src/regexp/regexp.go:533
github.com/air-verse/air/runner.(*Engine).isExcludeRegex(0xc000222000?, {0xc0000b2780, 0x5d})
        /Users/lidldev/go/pkg/mod/github.com/air-verse/air@v1.61.0/runner/util.go:167 +0xcb
github.com/air-verse/air/runner.(*Engine).watchPath.func1()
        /Users/lidldev/go/pkg/mod/github.com/air-verse/air@v1.61.0/runner/engine.go:256 +0x3ec
created by github.com/air-verse/air/runner.(*Engine).watchPath in goroutine 1
        /Users/lidldev/go/pkg/mod/github.com/air-verse/air@v1.61.0/runner/engine.go:223 +0x23f
```

**Comment by istyf** [comment] 2024-11-01 21:01
This seems to be a duplicate of #655

**Comment by temidaradev** [comment] 2024-11-02 09:38
> This seems to be a duplicate of #655 

Thanks!

**Closed** 2024-11-02 09:38 UTC
