### ISSUE TITLE
panic: unaligned 64-bit atomic operation in windows

### ISSUE THREAD

**Issue by liangruifeng** [air-verse/air#583] opened 2024-05-11 06:45 UTC
PS E:\test\ginlearn> air

  __    _   ___
 / /\  | | | |_)
/_/--\ |_| |_| \_ v1.52.0, built with Go go1.22.3

watching .
!exclude tmp
building...
running...
panic: unaligned 64-bit atomic operation

goroutine 18 [running]:
runtime/internal/atomic.panicUnaligned()
        C:/Users/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.windows-386/src/runtime/internal/atomic/unaligned.go:8 +0x2b
runtime/internal/atomic.Xadd64(0x2027b7c, 0x1)
        C:/Users/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.3.windows-386/src/runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/cosmtrek/air/runner.(*Engine).runBin.func2()
        C:/Users/go/pkg/mod/github.com/cosmtrek/air@v1.52.0/runner/engine.go:550 +0x335
created by github.com/cosmtrek/air/runner.(*Engine).runBin in goroutine 10
        C:/Users/go/pkg/mod/github.com/cosmtrek/air@v1.52.0/runner/engine.go:522 +0xd3

**Comment by liangruifeng** [comment] 2024-05-11 06:51
btw, my windows is 64-bit

**Comment by wangyupo** [comment] 2024-05-28 08:02
这个问题我也遇到了，版本：air v1.52.0, built with Go go1.22.3

**Comment by xiantang** [comment] 2024-05-28 08:28
find out the root cause, will fix in next version tks

**Comment by ndyabagye** [comment] 2024-06-04 07:20
Hello, I am on a Windows 11 Amd Ryzen 3 7320U and I am facing the same issue when I run the `air` command.

### CODE BELOW

```
air

  __    _   ___  
 / /\  | | | |_) 
/_/--\ |_| |_| \_ v1.52.2, built with Go go1.22.3

watching .
watching controllers
watching initializers
watching models
!exclude tmp
building...
!exclude .git
!exclude .git
running...
panic: unaligned 64-bit atomic operation

goroutine 23 [running]:
runtime/internal/atomic.panicUnaligned()
        C:/Program Files (x86)/Go/src/runtime/internal/atomic/unaligned.go:8 +0x2b
runtime/internal/atomic.Xadd64(0x2031b0c, 0x1)
        C:/Program Files (x86)/Go/src/runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/air-verse/air/runner.(*Engine).runBin.func2()
        C:/Users/henry/go/pkg/mod/github.com/air-verse/air@v1.52.2/runner/engine.go:550 +0x335
created by github.com/air-verse/air/runner.(*Engine).runBin in goroutine 22
        C:/Users/henry/go/pkg/mod/github.com/air-verse/air@v1.52.2/runner/engine.go:522 +0xd3
```

**Comment by xiantang** [comment] 2024-06-04 07:38
got that, wil fixed within this week

**Closed** 2024-06-23 12:05 UTC
